routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//SetLocale
Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl(); //URL предыдущей страницы
    $parse_url = parse_url($referer, PHP_URL_PATH); //URI предыдущей страницы

    //разбиваем на массив по разделителю
    $segments = explode('/', $parse_url);

    //Если URL (где нажали на переключение языка) содержал корректную метку языка
    if (in_array($segments[1], App\Http\Middleware\LocaleMiddleware::$languages)) {

        unset($segments[1]); //удаляем метку
    } 
    
    //Добавляем метку языка в URL (если выбран не язык по-умолчанию)
    if ($lang != App\Http\Middleware\LocaleMiddleware::$mainLanguage){ 
        array_splice($segments, 1, 0, $lang); 
    }

    //формируем полный URL
    $url = Request::root().implode("/", $segments);
    //если были еще GET-параметры - добавляем их
    if(parse_url($referer, PHP_URL_QUERY)){    
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }

    if(substr($url, -1) == "/"){
        $url = substr_replace($url, "", -1);
    }
    
    return redirect($url); //Перенаправляем назад на ту же страницу                            

})->name('setlocale');

//Main
Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){
    Route::get('/', 'PageController@index')->name('page.home');
    Route::get('/about', 'PageController@about')->name('page.about');
    Route::get('/services', 'PageController@services')->name('page.services');
    Route::get('/services/{service}', 'PageController@serviceDetails')->name('page.serviceDetails');

//    Route::get('news/{news}', 'PagesController@fullNewsPage')->name('fullNewsPage');
    Route::get('/articles', 'PageController@articles')->name('page.articles');
    Route::get('/articles/{article}', 'PageController@articleDetails')->name('page.articleDetails');
    Route::get('/login', 'PageController@login')->name('login');

    //Сonsultation
    Route::get('/consultation', 'ConsultationController@infoPage')->name('page.consultation');
    Route::get('/consultation-request', 'ConsultationController@requestFormPage')->name('page.consultation-request');
    Route::post('/consultation/store-request', 'ConsultationController@storeRequest')->name('page.consultation-store');
    Route::get('/consultation/success-message', 'ConsultationController@successMessage')->name('page.consultation-success-message');

    Route::get('/terms-of-use', 'PageController@termsOfUse')->name('page.terms-of-use');
    Route::get('/privacy-policy', 'PageController@privacyPolicy')->name('page.privacy-policy');

});


//Login
Route::get('/logout', 'UsersController@logout')->name('logout');
Route::get('/logout-form', 'UsersController@logout_form')->name('logout-form');
Route::post('/admin-panel', 'UsersController@authenticate')->name('authenticate');

//Admin-panel
Route::group(['prefix'=>'admin-panel', 'middleware'=>'auth'], function (){
    Route::get('/', 'ArticlesController@index');

    //Article
    Route::post('articles/select', 'ArticlesController@selectBlog')->name('articles.list');
    Route::get('articles/{article}/delete', 'ArticlesController@delete')->name('articles.delete');
    Route::resource('articles', 'ArticlesController');

    //Service
    Route::post('services/select', 'ServicesController@selectServices')->name('services.list');
    Route::get('services/{services}/delete', 'ServicesController@delete')->name('services.delete');
    Route::resource('services', 'ServicesController');

    //Users
    Route::get('users/profile', 'UsersController@profile')->name('users.profile');
    Route::get('users/{users}/password', 'UsersController@password')->name('users.password');
    Route::post('users/{users}/change-password', 'UsersController@changePassword')->name('users.change-password');

    Route::resource('users', 'UsersController');

    //Consultation
    Route::group(['prefix'=>'consultation', 'as' => 'consultation.'], function (){
        
        //Services
        Route::resource('services', 'admin\consultation\ConsultationServiceController');
        Route::post('services/select', 'admin\consultation\ConsultationServiceController@selectService')->name('services.list');
        Route::get('services/{service}/delete', 'admin\consultation\ConsultationServiceController@delete')->name('services.delete');

        //Requests
        Route::get('requests', 'admin\consultation\ConsultationRequestController@index')->name('requests.index');
        Route::post('requests/select', 'admin\consultation\ConsultationRequestController@selectRequest')->name('requests.list');
        Route::get('requests/details/{request}', 'admin\consultation\ConsultationRequestController@details')->name('requests.details');
        Route::get('requests/{request}/delete', 'admin\consultation\ConsultationRequestController@delete')->name('requests.delete');
        Route::delete('requests/{request}', 'admin\consultation\ConsultationRequestController@destroy')->name('requests.destroy');

    });
});

app/Consultation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Consultation extends Model
{
    //
}

app/Http/Controllers/ConsultationController.php
<?php

namespace App\Http\Controllers;

use App\Practice;
use Illuminate\Support\Facades\App;
use Illuminate\Http\Request;

use App\ConsultationService;
use App\Consultation;
use App\Http\Requests\StoreConsultationRequest;
use App\Mail\AdminConsultationNotificationEmail;
use Illuminate\Support\Facades\Mail;

class ConsultationController extends Controller
{
    
    private $footerServices = [];

    public function __construct()
    {
        $this->footerServices = Practice::where('lang', App::getLocale())->orderby('priority', 'asc')->take(5)->get();
    }

    /**
     * Show consultation info page.
     * @return view
     */
    public function infoPage ()
    {
        $data['title'] = __('words.site_name') . ' - ' . __('words.nav_contact');
        $data['active_page'] = 'contact';
        $data['footerServices'] = $this->footerServices;

        return view('consultation.info', $data);
    }

    public function requestFormPage()
    {
        $data['title'] = __('words.site_name') . ' - ' . __('words.nav_contact');
        $data['active_page'] = 'contact';
        $data['footerServices'] = $this->footerServices;
        $data['services'] = ConsultationService::orderBy('priority', 'ASC')->get();

        return view('consultation.request-form', $data);

    }

    public function storeRequest(StoreConsultationRequest $request)
    {
        //prepare services array in necessary format 
        $consultationService = [];
        foreach (ConsultationService::select('id', 'price')->get() as $item) {
            $consultationService[$item->id] = $item->price;
        }

        //prepare services and hours data with total sum  
        $paid_sum = 0;
        $services = [];
         foreach ($request->services as $item) {
            $hours = $request->input('services_hours_' . $item);
            array_push($services, ['service_id' => $item, 'hours' => $hours]);
            
            $paid_sum += $consultationService[$item] * $hours;
         }

         $consultation = new Consultation();

         $consultation->name = $request->name;
         $consultation->surname = $request->surname;
         $consultation->phone = $request->phone;
         $consultation->email = $request->email;
         $consultation->subject = $request->subject;
         $consultation->subject = $request->subject;
         $consultation->communication_type = $request->communication_mode;
         $consultation->services = json_encode($services);
         $consultation->paid_sum = $paid_sum;

         if ($consultation->save()) {
            Mail::to(config('app.admin_mail'))->send(new AdminConsultationNotificationEmail());

            return response()->json([
                'message' => "Cerere a fost adăugata",
                'redirect' => route('page.consultation-success-message'),
    
            ], 200);
         }
    }

        /**
     * Show page with success message
     * @return view
     */
    public function successMessage()
    {
        $data['title'] = __('words.site_name') . ' - ' . 'Success';
        $data['active_page'] = 'Success';
        $data['footerServices'] = $this->footerServices;

        return view('consultation.success-message', $data);
    }

}

app/Http/Controllers/ServicesController.php
<?php

namespace App\Http\Controllers;

use App\Practice;
use App\Helpers\Alias;
use App\Helpers\MyImage;
use Illuminate\Http\Request;

class ServicesController extends Controller
{
    private $table = "practices";
    private $imageWidth = 1280;
    private $imageHeight = 720;


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.services.index', ['activePage' => "services"]);
    }

    /**
     * Data table all records
     * @return JSON
     */
    public function selectServices()
    {
        
        $query = Practice::select('id', 'title', 'created_at', 'image', 'description', 'lang', 'priority', 'alias');

        return datatables($query)
            ->order(function ($query) {
                $columns = array(
                    1 => 'title',
                    3 => 'created_at',
                    5 => 'priority'
                );

                $dir = request()->order[0]['dir'];
                $col =  $columns[intval(request()->order[0]['column'])];

                $query->orderBy($col, $dir);
            })
            ->rawColumns(['actions', 'date', 'image'])
            ->addColumn('actions', 'admin.services.actions')
            ->addColumn('image', 'admin.services.image')

            ->addColumn('date', function($query){
                return date('d.m.Y', strtotime($query->created_at));
            })

            ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.services.form', ['activePage' => "services"]);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|unique:' . $this->table . '|max:255' ,
            'text' => 'required',
            'lang' => 'required',
            'description' => 'required|max:255',
        ]);

        $input = $request->all();

        $input['alias'] = Alias::generateAlias($input['title']);

        if($request->hasFile('image')){
            $image = $request->file('image');
            $input['image'] =  uniqid() . '.' . $image->getClientOriginalExtension();

            MyImage::saveImage($image->getRealPath(), public_path('images/services/'),  $input['image'], $this->imageWidth, $this->imageHeight);
        }

        $practice = new Practice();
        $practice->fill($input);
        $practice->save();

        return response()->json([
            'message' => "Serviciu a fost adăugata"
        ], 201);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.services.form',['activePage' => "services", 'services' => Practice::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required|unique:' . $this->table . ',title,'.$request['id'] . '|max:255',
            'text' => 'required',
            'lang' => 'required',
            'description' => 'required|max:255',
        ]);

        $input = $request->all();
        $input['alias'] = Alias::generateAlias($input['title']);

        if($request->hasFile('image')){
            $image = $request->file('image');
            $input['image'] =  uniqid() . '.' . $image->getClientOriginalExtension();

            MyImage::saveImage($image->getRealPath(), public_path('images/services/'),  $input['image'], $this->imageWidth, $this->imageHeight);

            if(isset($input['old_image']) && !empty($input['old_image'])){
                MyImage::deleteImage(public_path('images/services/'), $input['old_image']);
            }

        }elseif(isset($input['old_image']) && !empty($input['old_image'])){
            $input['image'] = $input['old_image'];
        }

        $practice = Practice::findOrFail($id);
        $practice->fill($input);
        $practice->update();

        return response()->json([
            'message' => "Serviciu au fost actualizata"
        ], 201);
    }

    /**
     * Show the form for deleting a resource.
     *
     * @param  int  $id
     * @return view
     */
    public function delete($id)
    {
        return view('admin.services.delete', Practice::findOrFail($id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->ajax()){
            $practice = Practice::findOrFail($id);

            if(isset($practice['image']) && !empty($practice['image'])){
                MyImage::deleteImage(public_path('images/services/'), $practice['image']);
            }

            $practice->delete();

            return response()->json([
                'message' => 'Serviciu a fost ștearsa'
            ], 200);
        }
        abort(404);
    }
}

app/Http/Controllers/admin/consultation/ConsultationRequestController.php
<?php

namespace App\Http\Controllers\admin\consultation;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Consultation;
use App\ConsultationService;


class ConsultationRequestController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() 
    {
        return view('admin.consultation.requests.index', ['activePage' => "consultation-request"]);
    }

    /**
     * Display a JSON listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function selectRequest() 
    {
        $query = Consultation::select('id', 'name', 'surname', 'phone', 'email', 'subject', 'paid', 'created_at');

        return datatables($query)
            ->order(function ($query) {
                $columns = array(
                    0 => 'surname',
                    5 => 'created_at'
                );

                $dir = request()->order[0]['dir'];
                $col =  $columns[intval(request()->order[0]['column'])];

                $query->orderBy($col, $dir);
            })
            ->rawColumns(['full_name', 'services', 'paid', 'actions', 'date'])
        
            ->addColumn('full_name', function($query){
                return $query->surname . ' ' . $query->name;
            })

            // 'admin.consultation.requests.services'
            ->addColumn('date', function($query){
                return date('d.m.Y', strtotime($query->created_at));
            })

            ->addColumn('actions', 'admin.consultation.requests.actions')

            ->addColumn('paid', 'admin.consultation.requests.paid-state')

            ->toJson();
    }

    /**
     * Display a detail page of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function details (int $id)
    {
        //prepare services array in necessary format 
        $consultationService = [];
        foreach (ConsultationService::select('id', 'title', 'price')->get() as $item) {
            $consultationService[$item->id] = ['title' => $item->title,'price' => $item->price];
        }

        $request = Consultation::findOrFail($id);
        $services = json_decode($request->services, true);

        return view('admin.consultation.requests.details', compact('request', 'services', 'consultationService'));
    }

        /**
     * Show the form for deleting a resource.
     *
     * @param  int  $id
     * @return view
     */
    public function delete($id)
    {
        return view('admin.consultation.requests.delete', compact('id'));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->ajax()){
            $service = Consultation::findOrFail($id);

            $service->delete();

            return response()->json([
                'message' => 'Cerere a fost stearsa'
            ], 200);
        }

        abort(404);
    }
}

resources/views/admin/consultation/services/actions.blade.php
<a href="{{ route('consultation.services.edit', $id) }}" class="btn btn-primary"><i class="fa fa-fw fa-pencil"></i></a>
<a data-fancybox data-type="ajax" data-src="{{ route('consultation.services.delete', $id) }}" href="javascript:;" class="btn btn-danger"><i class="fa fa-fw fa-trash"></i></a>

resources/views/admin/consultation/services/delete.blade.php
<div style="width:300px">

    <div class="col-md-12">

        <form method="POST" class="form-horizontal" id="service_delete" action="{{ route('consultation.services.destroy', $id) }}">
            {!! csrf_field() !!}
            <input type="hidden" name="_method" value="DELETE">

            <div class="panel-heading ui-draggable-handle">
                <h3 class="panel-title"><strong>Șterge serviciul</strong></h3>
                <div class="panel-body">
                    <p>Ești sigur?</p>
                </div>
            </div>

            <button class="btn btn-default" id="cancel">Anulare</button>
            <button class="btn btn-danger pull-right" type="submit">Da</button>
        </form>
    </div>
</div>


<script>

    var url = $('#service_delete').attr('action');

    $('#cancel').on('click', function(){
        $.fancybox.close();
        return false;
    });

    $("#service_delete").submit(function(e){
        e.preventDefault();

        $.post(url, $('#service_delete').serialize(), null, 'json').done(function(response) {
            new Noty({type: 'success', layout: 'topRight', text: response.message, timeout:3000}).show();

            $.fancybox.close();

            if(dt) {
                dt.draw(false)
            }
        }).fail(onSaveRequestError);

    });
</script>

resources/views/admin/consultation/services/form.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="panel-title">{{ !empty($service->id) ? 'Editarea' : 'Adăuga' }} serviciu</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="col-md-12">
                <form method="POST" action="{{ !empty($service->id) ? route('consultation.services.update', ['service' => $service->id]) : route('consultation.services.store') }}" class="form-horizontal" id="service-form">
                    {!! csrf_field() !!}

                    @if(!empty($service->id))
                        <input type="hidden" name="_method" value="PUT">
                    @endif

                    <div class="form-group">
                        <label for="title">Titlu</label>
                        <input type="text" class="form-control validate[required, maxSize[250]]" id="title" name="title" placeholder="Title:" value="{{ !empty($service->title) ? $service->title : '' }}">
                    </div>

                    <div class="form-group">
                        <label for="title">Preț pe ora</label>
                        <input type="number" class="form-control validate[required, onlyNumber]" min="0" id="price" name="price" placeholder="Preț pe ora:" value="{{ !empty($service->price) ? $service->price : '' }}">
                    </div>

                    <div class="form-group">
                        <label for="priority">Prioritate</label>
                        <input type="number" class="form-control" min="0" id="priority" name="priority" placeholder="Prioritate:" value="{{ !empty($service->priority) ? $service->priority : '' }}">
                    </div>

                    <button class="btn btn-default" type="reset">Curăța</button>
                    <button class="btn btn-primary pull-right" type="submit">Adăuga</button>

                </form>
            </div>
        </div>
        <!-- /.box-body -->
        <!-- /.box-body -->
    </div>

    <script>
        $( document ).ready(function() {

            $("#service-form").validationEngine({
                promptPosition : "topLeft",
                onValidationComplete: function(form, status){
                    if(status){

                        $.ajax ({
                            url : $('#service-form').attr('action'),
                            type: 'POST',
                            data: new FormData($('#service-form')[0]),
                            dataType: 'JSON',
                            contentType: false, // NEEDED, DON'T OMIT THIS (requires jQuery 1.6+)
                            processData: false, // NEEDED, DON'T OMIT THIS
                            success: function (response) {
                                // new Noty({type: 'success', layout: 'topRight', text: response.message, timeout:3000}).show();
                                document.location.href = '{{ route('consultation.services.index') }}';

                            },
                            error: function (error) {
                                onSaveRequestError(error);
                            }
                        })

                    }
                }
            });
        })

    </script>
@endsection

resources/views/admin/consultation/services/index.blade.php
@extends('layouts.admin')

@section('content')
@include('admin.components.success-message')

    <div class="box">
        <div class="box-header">
            <h3 class="box-title">CONSULTANȚĂ Servicii</h3>
            <div class="box-tools">
                <a href="{{ route('consultation.services.create') }}" class="btn btn-block btn-primary "><i class="fa fa-fw fa-plus"></i> Adăuga serviciu</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="blog_table" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                <thead>
                <tr role="row">
                    <th>Titlu</th>
                    <th>Preț pe ora</th>
                    <th>Prioritate</th>
                    <th>Data</th>
                    <th>Acţiuni</th>
                </tr>
                </thead>
                <tbody>

                </tbody>

            </table>
        </div>
        <!-- /.box-body -->
        <!-- /.box-body -->
    </div>
    <script>

        var dt;
        $(document).ready(function() {
            dt = $('#blog_table').DataTable( {
                "processing": true,
                "serverSide": true,
                "autoWidth": false,
                responsive: true,
                stateSave: true,
                "order": [ 3, 'desc' ],
                "language": {
                    "lengthMenu": "_MENU_ pe pagina",
                    "zeroRecords": "Nimic nu a fost găsit - îmi pare rău",
                    "info": "Pagina _PAGE_ din _PAGES_",
                    "infoEmpty": "Nu există înregistrări disponibile",
                    "infoFiltered": "(filtrarea a _MAX_ intrări)",
                    "sSearch": "Caută:",
                    "oPaginate": {
                        "sFirst":    "Prima",
                        "sLast":    "Ultima",
                        "sNext":    "Următoarea",
                        "sPrevious": "Precedenta"
                    }
                },
                "columnDefs": [
                    {orderable: true,  searchable: true, "targets": 0},
                    {orderable: false, searchable: true, className: "w-100", searchable: false, "targets": 1},
                    {orderable: true,  searchable: true, className: "w-100", searchable: false, "targets": 2},
                    {orderable: false, searchable: true, className: "w-50", searchable: false, "targets": 3},
                    {orderable: false, className: "w-150", searchable: false, "targets": 4},

                ],
                "columns": [
                    {"data": "title"},
                    {"data": "price"},
                    {"data": "priority"},
                    {"data": "date"},
                    {"data": "actions"},

                ],

                "ajax": {
                    url: "{{route('consultation.services.list')}}",
                    type: 'POST',
                }
            });
        });
    </script>
@endsection