routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//SetLocale
Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl(); //URL предыдущей страницы
    $parse_url = parse_url($referer, PHP_URL_PATH); //URI предыдущей страницы

    //разбиваем на массив по разделителю
    $segments = explode('/', $parse_url);

    //Если URL (где нажали на переключение языка) содержал корректную метку языка
    if (in_array($segments[1], App\Http\Middleware\LocaleMiddleware::$languages)) {

        unset($segments[1]); //удаляем метку
    } 
    
    //Добавляем метку языка в URL (если выбран не язык по-умолчанию)
    if ($lang != App\Http\Middleware\LocaleMiddleware::$mainLanguage){ 
        array_splice($segments, 1, 0, $lang); 
    }

    //формируем полный URL
    $url = Request::root().implode("/", $segments);
    //если были еще GET-параметры - добавляем их
    if(parse_url($referer, PHP_URL_QUERY)){    
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }

    if(substr($url, -1) == "/"){
        $url = substr_replace($url, "", -1);
    }
    
    return redirect($url); //Перенаправляем назад на ту же страницу                            

})->name('setlocale');

//Main
Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){
    Route::get('/', 'PageController@index')->name('page.home');
    Route::get('/about', 'PageController@about')->name('page.about');
    Route::get('/services', 'PageController@services')->name('page.services');
    Route::get('/services/{service}', 'PageController@serviceDetails')->name('page.serviceDetails');

//    Route::get('news/{news}', 'PagesController@fullNewsPage')->name('fullNewsPage');
    Route::get('/articles', 'PageController@articles')->name('page.articles');
    Route::get('/articles/{article}', 'PageController@articleDetails')->name('page.articleDetails');
    Route::get('/login', 'PageController@login')->name('login');

    //Сonsultation
    Route::get('/consultation', 'ConsultationController@infoPage')->name('page.consultation');
    Route::get('/consultation-request', 'ConsultationController@requestFormPage')->name('page.consultation-request');
    Route::post('/consultation/store-request', 'ConsultationController@storeRequest')->name('page.consultation-store');
    Route::get('/consultation/success-message', 'ConsultationController@successMessage')->name('page.consultation-success-message');

    Route::get('/terms-of-use', 'PageController@termsOfUse')->name('page.terms-of-use');
    Route::get('/privacy-policy', 'PageController@privacyPolicy')->name('page.privacy-policy');

});


//Login
Route::get('/logout', 'UsersController@logout')->name('logout');
Route::get('/logout-form', 'UsersController@logout_form')->name('logout-form');
Route::post('/admin-panel', 'UsersController@authenticate')->name('authenticate');

//Admin-panel
Route::group(['prefix'=>'admin-panel', 'middleware'=>'auth'], function (){
    Route::get('/', 'ArticlesController@index');

    //Article
    Route::post('articles/select', 'ArticlesController@selectBlog')->name('articles.list');
    Route::get('articles/{article}/delete', 'ArticlesController@delete')->name('articles.delete');
    Route::resource('articles', 'ArticlesController');

    //Service
    Route::post('services/select', 'ServicesController@selectServices')->name('services.list');
    Route::get('services/{services}/delete', 'ServicesController@delete')->name('services.delete');
    Route::resource('services', 'ServicesController');

    //Users
    Route::get('users/profile', 'UsersController@profile')->name('users.profile');
    Route::get('users/{users}/password', 'UsersController@password')->name('users.password');
    Route::post('users/{users}/change-password', 'UsersController@changePassword')->name('users.change-password');

    Route::resource('users', 'UsersController');

    //Consultation
    Route::group(['prefix'=>'consultation', 'as' => 'consultation.'], function (){
        
        //Services
        Route::resource('services', 'admin\consultation\ConsultationServiceController');
        Route::post('services/select', 'admin\consultation\ConsultationServiceController@selectService')->name('services.list');
        Route::get('services/{service}/delete', 'admin\consultation\ConsultationServiceController@delete')->name('services.delete');

        //Requests
        Route::get('requests', 'admin\consultation\ConsultationRequestController@index')->name('requests.index');
        Route::post('requests/select', 'admin\consultation\ConsultationRequestController@selectRequest')->name('requests.list');
        Route::get('requests/details/{request}', 'admin\consultation\ConsultationRequestController@details')->name('requests.details');
        Route::get('requests/{request}/delete', 'admin\consultation\ConsultationRequestController@delete')->name('requests.delete');
        Route::delete('requests/{request}', 'admin\consultation\ConsultationRequestController@destroy')->name('requests.destroy');

    });
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable=['title', 'alias', 'text', 'image', 'youtube_video', 'id_author', 'lang', 'description'];
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Helpers\Alias;
use App\Helpers\MyImage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ArticlesController extends Controller
{
    private $table = "articles";
    private $imageWidth = 1280;
    private $imageHeight = 720;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    { 
        return view('admin.articles.index', ['activePage' => "articles"]);
    }

    /**
     * Data table all records
     * @return JSON
     */
    public function selectBlog()
    {
        $query = Article::select('id', 'title', 'created_at', 'image', 'description', 'lang', 'alias');

        return datatables($query)
            ->order(function ($query) {
                $columns = array(
                    1 => 'title',
                    3 => 'created_at'
                );

                $dir = request()->order[0]['dir'];
                $col =  $columns[intval(request()->order[0]['column'])];

                $query->orderBy($col, $dir);
            })
            ->rawColumns(['actions', 'date', 'image'])
            ->addColumn('actions', 'admin.articles.actions')
            ->addColumn('image', 'admin.articles.image')

            ->addColumn('date', function($query){
                return date('d.m.Y', strtotime($query->created_at));
            })

            ->toJson();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.form', ['activePage' => "articles"]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title'       => 'required|unique:' . $this->table . '|max:255' ,
            'text'        => 'required',
            'lang'        => 'required',
            'description' => 'required|max:255',
        ]);

        $input = $request->all();
        $input['alias'] = Alias::generateAlias($input['title']);

        if($request->hasFile('image')){
            $image = $request->file('image');
            $input['image'] =  uniqid() . '.' . $image->getClientOriginalExtension();

            MyImage::saveImage($image->getRealPath(), public_path('images/articles/'),  $input['image'], $this->imageWidth, $this->imageHeight);
        }

        $article = new Article();
        $article->fill($input);
        $article->save();

        return response()->json([
            'message' => "Articol a fost adăugat"
        ], 201);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('admin.articles.form',['activePage' => "articles", "article" => Article::findOrFail($id)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title'       => 'required|unique:' . $this->table . ',title,'.$request['id'] . '|max:255',
            'text'        => 'required',
            'lang'        => 'required',
            'description' => 'required|max:255',
        ]);

        $input = $request->all();
        $input['alias'] = Alias::generateAlias($input['title']);

        if($request->hasFile('image')){
            $image = $request->file('image');
            $input['image'] =  uniqid() . '.' . $image->getClientOriginalExtension();

            MyImage::saveImage($image->getRealPath(), public_path('images/articles/'),  $input['image'], $this->imageWidth, $this->imageHeight);

            if(isset($input['old_image']) && !empty($input['old_image'])){
                MyImage::deleteImage(public_path('images/articles/'), $input['old_image']);
            }

        }elseif(isset($input['old_image']) && !empty($input['old_image'])){
            $input['image'] = $input['old_image'];
        }

        $article = Article::findOrFail($id);
        $article->fill($input);
        $article->update();

        return response()->json([
            'message' => "Articol au fost actualizat"
        ], 201);
    }

    /**
     * Show the form for deleting a resource.
     *
     * @param  int  $id
     * @return view
     */
    public function delete($id)
    {
        return view('admin.articles.delete', Article::findOrFail($id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if($request->ajax()){
            $article = Article::findOrFail($id);

            if(isset($article['image']) && !empty($article['image'])){
                MyImage::deleteImage(public_path('images/articles/'), $article['image']);
            }

            $article->delete();

            return response()->json([
                'message' => 'Articol a fost șters'
            ], 200);
        }
        abort(404);
    }
}

resources/views/admin/articles/actions.blade.php
<a href="{{ route('page.articleDetails', ['service' => $alias]) }}" class="btn btn-default" target="_blank"><i class="fa fa-fw fa-link"></i></a>
<a href="{{ route('articles.edit', $id) }}" class="btn btn-primary"><i class="fa fa-fw fa-pencil"></i></a>
<a data-fancybox data-type="ajax" data-src="{{ route('articles.delete', $id) }}" href="javascript:;" class="btn btn-danger"><i class="fa fa-fw fa-trash"></i></a>

resources/views/admin/articles/delete.blade.php
<div style="width:300px">

    <div class="col-md-12">

        <form method="POST" class="form-horizontal" id="blog_delete">
            {!! csrf_field() !!}
            <?php if(!empty($id)){?>
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" id='id' name="id" value="{{$id}}">
            <?php }?>

            <div class="panel-heading ui-draggable-handle">
                <h3 class="panel-title"><strong>Șterge articol</strong></h3>
                <div class="panel-body">
                    <p>Ești sigur?</p>
                </div>
            </div>

            <button class="btn btn-default" id="cancel">Anulare</button>
            <button class="btn btn-danger pull-right" type="submit">Da</button>
        </form>
    </div>
</div>


<script>
    var id = $('#id'). val();
    var url = '/admin-panel/articles/' + id;

    $('#cancel').on('click', function(){
        $.fancybox.close();
        return false;
    });

    $("#blog_delete").submit(function(e){
        e.preventDefault();

        $.post(url, $('#blog_delete').serialize(), null, 'json').done(function(response) {
            new Noty({type: 'success', layout: 'topRight', text: response.message, timeout:3000}).show();

            $.fancybox.close();

            if(dt) {
                dt.draw(false)
            }
        }).fail(onSaveRequestError);

    });
</script>

resources/views/admin/articles/form.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="panel-title">{{!empty($article->id) ? 'Editarea' : 'Adăuga'}} articol</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <div class="col-md-12">
                <form method="POST" action="{{!empty($article->id) ? route('articles.update', ['article' => $article->id]) : route('articles.store')}}" class="form-horizontal" id="article_form" enctype="multipart/form-data">
                    {!! csrf_field() !!}

                    <?php if(!empty($article->id)){?>
                    <input type="hidden" name="_method" value="PUT">
                    <input type="hidden" id='id' name="id" value="{{$article->id}}">
                    <?php }?>

                    <div class="form-group">
                        <label for="title">Title</label>
                        <input type="text" class="form-control validate[required, maxSize[250]]" id="title" name="title" placeholder="Title:" value="{{!empty($article->title) ? $article->title : ''}}">
                    </div>

                    <div class="form-group">
                        <label for="description">Descriere</label>
                        <textarea class="form-control validate[required, maxSize[250]]" id="description" name="description" rows="4" cols="80" style="resize: none" placeholder="Descriere:">{{!empty($article->description) ? $article->description : ''}}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="editor">Text</label>
                        <textarea class="validate[required]" id="editor" name="text" rows="10" cols="80">{{!empty($article->text) ? $article->text : ''}}</textarea>
                    </div>

                    <div class="form-group">
                        <label>Limba</label>
                        <select class="form-control validate[required]" name="lang">
                            @if(empty($article->lang))
                                <option value="" selected>Selecteaza limba</option>
                            @endif

                            <option value="ru" {{ (!empty($article->lang) && $article->lang == "ru") ? "selected" : "" }}>RU</option>
                            <option value="ro" {{ (!empty($article->lang) && $article->lang == "ro") ? "selected" : "" }}>RO</option>
                        </select>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="image">Imaginea</label>
                            <input type="file" id="image" name="image">

                        </div>

                        @if(isset($article->image) && !empty($article->image))
                            <img src="/public/images/articles/{{ $article->image }}" width="400px" height="200px">
                            <input type="hidden" value="{{ $article->image }}" name="old_image">
                        @elseif(isset($article->id) && !empty($article->id))
                            <img src="/public/images/noImg.jpg" width="200px">
                        @endif

                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="video">Video</label>
                            <input type="text" class="form-control" id="video" name="youtube_video" value="{{!empty($article->youtube_video) ? $article->youtube_video : ''}}" placeholder="Introduceti ID pentru video de pe YouTube:">
                            <span class="help-block">Introduceti ID pentru video de pe YouTube</span>
                        </div>

                        @if(isset($article->youtube_video) && !empty($article->youtube_video))
                            <iframe width="400px" height="200px" src="https://www.youtube.com/embed/{{ $article->youtube_video }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

                        @endif

                    </div>

                    <button class="btn btn-default" type="reset">Curăța</button>
                    <button class="btn btn-primary pull-right" type="submit">Adăuga</button>

                </form>
            </div>
        </div>
        <!-- /.box-body -->
        <!-- /.box-body -->
    </div>

    <script>
        $( document ).ready(function() {
            tinymce.init({
                selector: '#editor',
                entity_encoding: 'raw',
                menubar: false,
                branding: false,
                height: 500,
                max_height: 700,
                min_height: 500,
                plugins: [
                    'autolink autoresize fullscreen link lists paste',
                ],
                toolbar: 'undo redo | bold italic | underline strikethrough | bullist numlist | link | fullscreen',

                link_assume_external_targets: true,
                relative_urls: false,
                image_advtab: true ,
                remove_script_host: false,
                force_br_newlines: false,
                force_p_newlines: false,
                forced_root_block: "",
                extended_valid_elements: "br",
                verify_html: false,
                valid_children: "br",
                paste_as_text: true,

            });

            $("#article_form").validationEngine({
                promptPosition : "topLeft",
                onValidationComplete: function(form, status){
                    if(status){

                        $.ajax ({
                            url : $('#article_form').attr('action'),
                            type: 'POST',
                            data: new FormData($('#article_form')[0]),
                            dataType: 'JSON',
                            contentType: false, // NEEDED, DON'T OMIT THIS (requires jQuery 1.6+)
                            processData: false, // NEEDED, DON'T OMIT THIS
                            success: function (response) {
                                new Noty({type: 'success', layout: 'topRight', text: response.message, timeout:3000}).show();
                                document.location.href = '{{ route('articles.index') }}';

                                if(dt) {
                                    dt.draw(false)
                                }
                            },
                            error: function (error) {
                                onSaveRequestError(error);
                            }
                        })

                    }
                }
            });
        })

    </script>
@endsection

resources/views/admin/articles/image.blade.php
@if(isset($image) &&!empty($image))
    <img src="/public/images/articles/{{ $image }}" width="100px">
    @else
        <img src="/public/images/noImg.jpg" width="100px">
@endif

resources/views/admin/articles/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Articole</h3>
            <div class="box-tools">
                <a href="{{ route('articles.create') }}" class="btn btn-block btn-primary "><i class="fa fa-fw fa-plus"></i> Adăuga articol</a>
            </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="blog_table" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="example1_info">
                <thead>
                <tr role="row">
                    <th>Imaginea</th>
                    <th>Titlu</th>
                    <th>Descrierea</th>
                    <th>Data</th>
                    <th>Limba</th>
                    <th>Acţiuni</th>
                </tr>
                </thead>
                <tbody>

                </tbody>

            </table>
        </div>
        <!-- /.box-body -->
        <!-- /.box-body -->
    </div>
    <script>

        var dt;
        $(document).ready(function() {
            dt = $('#blog_table').DataTable( {
                "processing": true,
                "serverSide": true,
                "autoWidth": false,
                responsive: true,
                //"searching": false,
                stateSave: true,
                "order": [ 1, 'desc' ],
                "language": {
                    "lengthMenu": "_MENU_ pe pagina",
                    "zeroRecords": "Nimic nu a fost găsit - îmi pare rău",
                    "info": "Pagina _PAGE_ din _PAGES_",
                    "infoEmpty": "Nu există înregistrări disponibile",
                    "infoFiltered": "(filtrarea a _MAX_ intrări)",
                    "sSearch": "Caută:",
                    "oPaginate": {
                        "sFirst":    "Prima",
                        "sLast":    "Ultima",
                        "sNext":    "Următoarea",
                        "sPrevious": "Precedenta"
                    }
                },
                "columnDefs": [
                    {orderable: false, className: "w-50", "targets": 0},
                    {orderable: true,  searchable: true, "targets": 1},
                    {orderable: false, className: "w-300", searchable: false, "targets": 2},
                    {orderable: true, className: "w-100", searchable: false, "targets": 3},
                    {orderable: false, className: "w-50", searchable: false, "targets": 4},
                    {orderable: false, className: "w-150", searchable: false, "targets": 5},

                ],
                "columns": [
                    {"data": "image"},
                    {"data": "title"},
                    {"data": "description"},
                    {"data": "date"},
                    {"data": "lang"},
                    {"data": "actions"},

                ],

                "ajax": {
                    url: "{{route('articles.list')}}",
                    type: 'POST',
                }
            });
        });
    </script>
@endsection