routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//SetLocale
Route::get('setlocale/{lang}', function ($lang) {

    $referer = Redirect::back()->getTargetUrl(); //URL предыдущей страницы
    $parse_url = parse_url($referer, PHP_URL_PATH); //URI предыдущей страницы

    //разбиваем на массив по разделителю
    $segments = explode('/', $parse_url);

    //Если URL (где нажали на переключение языка) содержал корректную метку языка
    if (in_array($segments[1], App\Http\Middleware\LocaleMiddleware::$languages)) {

        unset($segments[1]); //удаляем метку
    } 
    
    //Добавляем метку языка в URL (если выбран не язык по-умолчанию)
    if ($lang != App\Http\Middleware\LocaleMiddleware::$mainLanguage){ 
        array_splice($segments, 1, 0, $lang); 
    }

    //формируем полный URL
    $url = Request::root().implode("/", $segments);
    //если были еще GET-параметры - добавляем их
    if(parse_url($referer, PHP_URL_QUERY)){    
        $url = $url.'?'. parse_url($referer, PHP_URL_QUERY);
    }

    if(substr($url, -1) == "/"){
        $url = substr_replace($url, "", -1);
    }
    
    return redirect($url); //Перенаправляем назад на ту же страницу                            

})->name('setlocale');

//Main
Route::group(['prefix' => App\Http\Middleware\LocaleMiddleware::getLocale()], function(){
    Route::get('/', 'PageController@index')->name('page.home');
    Route::get('/about', 'PageController@about')->name('page.about');
    Route::get('/services', 'PageController@services')->name('page.services');
    Route::get('/services/{service}', 'PageController@serviceDetails')->name('page.serviceDetails');

//    Route::get('news/{news}', 'PagesController@fullNewsPage')->name('fullNewsPage');
    Route::get('/articles', 'PageController@articles')->name('page.articles');
    Route::get('/articles/{article}', 'PageController@articleDetails')->name('page.articleDetails');
    Route::get('/login', 'PageController@login')->name('login');

    //Сonsultation
    Route::get('/consultation', 'ConsultationController@infoPage')->name('page.consultation');
    Route::get('/consultation-request', 'ConsultationController@requestFormPage')->name('page.consultation-request');
    Route::post('/consultation/store-request', 'ConsultationController@storeRequest')->name('page.consultation-store');
    Route::get('/consultation/success-message', 'ConsultationController@successMessage')->name('page.consultation-success-message');

    Route::get('/terms-of-use', 'PageController@termsOfUse')->name('page.terms-of-use');
    Route::get('/privacy-policy', 'PageController@privacyPolicy')->name('page.privacy-policy');

});


//Login
Route::get('/logout', 'UsersController@logout')->name('logout');
Route::get('/logout-form', 'UsersController@logout_form')->name('logout-form');
Route::post('/admin-panel', 'UsersController@authenticate')->name('authenticate');

//Admin-panel
Route::group(['prefix'=>'admin-panel', 'middleware'=>'auth'], function (){
    Route::get('/', 'ArticlesController@index');

    //Article
    Route::post('articles/select', 'ArticlesController@selectBlog')->name('articles.list');
    Route::get('articles/{article}/delete', 'ArticlesController@delete')->name('articles.delete');
    Route::resource('articles', 'ArticlesController');

    //Service
    Route::post('services/select', 'ServicesController@selectServices')->name('services.list');
    Route::get('services/{services}/delete', 'ServicesController@delete')->name('services.delete');
    Route::resource('services', 'ServicesController');

    //Users
    Route::get('users/profile', 'UsersController@profile')->name('users.profile');
    Route::get('users/{users}/password', 'UsersController@password')->name('users.password');
    Route::post('users/{users}/change-password', 'UsersController@changePassword')->name('users.change-password');

    Route::resource('users', 'UsersController');

    //Consultation
    Route::group(['prefix'=>'consultation', 'as' => 'consultation.'], function (){
        
        //Services
        Route::resource('services', 'admin\consultation\ConsultationServiceController');
        Route::post('services/select', 'admin\consultation\ConsultationServiceController@selectService')->name('services.list');
        Route::get('services/{service}/delete', 'admin\consultation\ConsultationServiceController@delete')->name('services.delete');

        //Requests
        Route::get('requests', 'admin\consultation\ConsultationRequestController@index')->name('requests.index');
        Route::post('requests/select', 'admin\consultation\ConsultationRequestController@selectRequest')->name('requests.list');
        Route::get('requests/details/{request}', 'admin\consultation\ConsultationRequestController@details')->name('requests.details');
        Route::get('requests/{request}/delete', 'admin\consultation\ConsultationRequestController@delete')->name('requests.delete');
        Route::delete('requests/{request}', 'admin\consultation\ConsultationRequestController@destroy')->name('requests.destroy');

    });
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>VM-Law - ADMIN</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{asset('AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('AdminLTE/bower_components/font-awesome/css/font-awesome.min.css')}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{asset('AdminLTE/bower_components/Ionicons/css/ionicons.min.css')}}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{asset('AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('AdminLTE/dist/css/AdminLTE.min.css')}}">
    <link rel="stylesheet" href="{{asset('AdminLTE/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">


    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('AdminLTE/dist/css/skins/_all-skins.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.css" />
    <link href="{{asset('plugins/Validation-Engine/css/validationEngine.jquery.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('plugins/croppie/croppie.css')}}" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.css"/>


    <link href="{{asset('plugins/noty/css/noty.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('plugins/noty/themes/mint.css')}}" rel="stylesheet" type="text/css" />

    <link href="{{asset('css/sizes.css')}}" rel="stylesheet" type="text/css" />

    <link href="{{asset('css/style_admin.css')}}" rel="stylesheet" type="text/css" />

    <script src="{{asset('AdminLTE/bower_components/jquery/dist/jquery.min.js')}}"></script>

    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>  
    
    <script src="{{asset('js/script_admin.js')}}"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="{{route('page.home')}}" class="logo" target="_blank">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini">VM</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">VM-Law</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
    
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
    
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @if(!empty(Auth::user()->image))
                                    <img src="{{asset('images/users') . '/' . Auth::user()->image}}" class="user-image" alt="{{Auth::user()->name}} {{Auth::user()->surname}}">
                                @else
                                    <img src="{{asset('images/noavatar.png')}}" class="user-image" alt="">
                                @endif

                                <span class="hidden-xs">{{Auth::user()->name}} {{Auth::user()->surname}}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">

                                    @if(!empty(Auth::user()->image))
                                        <img src="{{asset('images/users'). '/' . Auth::user()->image}}" class="img-circle" alt="{{Auth::user()->name}} {{Auth::user()->surname}}">
                                    @else
                                        <img src="{{asset('images/noavatar.png')}}" class="img-circle" alt="{{Auth::user()->name}} {{Auth::user()->surname}}">
                                    @endif
    
                                    <p>{{Auth::user()->name}} {{Auth::user()->surname}}</p>
                                </li>
    
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="{{route('users.profile')}}" class="btn btn-default btn-flat">Profil</a>
                                    </div>
                                    <div class="pull-right">
                                        <a data-fancybox data-type="ajax" data-src="{{ route('logout-form') }}" href="javascript:;" class="btn btn-default btn-flat">Ieșire</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
    
    
                    </ul>
                </div>
            </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <div class="user-panel">
                    <div class="pull-left image">
                        @if(!empty(Auth::user()->image))
                            <img src="{{asset('images/users') . '/' . Auth::user()->image}}" class="img-circle" alt="{{Auth::user()->name}} {{Auth::user()->surname}}">
                        @else
                            <img src="{{asset('images/noavatar.png')}}" class="img-circle" alt="">
                        @endif
                    </div>
                    <div class="pull-left info">
                        <p>{{Auth::user()->name}} {{Auth::user()->surname}}</p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">NAVIGARE</li>
                <li {{ (isset($activePage) && $activePage == "articles") ? "class=active" : "" }}><a href="{{route('articles.index')}}"><i class="fa fa-fw fa-newspaper-o"></i> <span> Articole</span></a></li>
                <li {{ (isset($activePage) && $activePage == "services") ? "class=active" : "" }}><a href="{{route('services.index')}}"><i class="fa fa-fw fa-legal"></i> <span> Servicii</span></a></li>

                <li class="treeview {{ isset($activePage) && in_array($activePage, ['consultation-request', 'consultation-service']) == 'services' ? 'active menu-open' : '' }}" style="height: auto;">
                    <a href="#">
                      <i class="fa fa-fw fa-phone"></i> <span>CONSULTANȚĂ</span>
                      <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                      </span>
                    </a>
                    <ul class="treeview-menu" {{ isset($activePage) && in_array($activePage, ['consultation-request', 'consultation-service']) == 'services' ? '' : 'style="display: none' }}>
                      <li {{ (isset($activePage) && $activePage == "consultation-service") ? "class=active" : "" }}><a href="{{ route('consultation.services.index') }}"><i class="fa fa-circle-o"></i> Servicii</a></li>
                      <li {{ (isset($activePage) && $activePage == "consultation-request") ? "class=active" : "" }}><a href="{{ route('consultation.requests.index') }}"><i class="fa fa-circle-o"></i> Cereri</a></li>
                    </ul>
                  </li>

                <li class="header">Setările profilului</li>
                <li {{ (isset($activePage) && $activePage == "profile") ? "class=active" : "" }}><a href="{{route('users.profile')}}"><i class="fa fa-fw fa-user    "></i></i> <span> Profil</span></a></li>
               

            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Panoul de administrare

            </h1>

        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Main row -->
            <div class="col-xs-12">


                @yield('content')
                <!-- right col -->

            </div>

            <!-- /.row (main row) -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      
        <strong>Copyright &copy; {{ date('Y') }} <a href="">Zagorcea Ion</a>.</strong>
    </footer>

    <div class="control-sidebar-bg"></div>
</div>


<!-- jQuery 3 -->
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('AdminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- DataTables -->
<script src="{{asset('AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<!-- SlimScroll -->
<script src="{{asset('AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<!-- FastClick -->
<script src="{{asset('AdminLTE/bower_components/fastclick/lib/fastclick.js')}}"></script>
<script src="{{asset('AdminLTE/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('AdminLTE/plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>

<script src="{{asset('AdminLTE/bower_components/fullcalendar/dist/fullcalendar.min.js')}}"></script>
<script src="{{asset('AdminLTE/bower_components/fullcalendar/dist/locale-all.js')}}"></script>

<script src="{{asset('plugins/noty/js/noty.js')}}"></script>

<script src="{{asset('plugins/Validation-Engine/js/jquery.validationEngine.js')}}"></script>
<script src="{{asset('plugins/Validation-Engine/js/jquery.validationEngine-ro.js')}}"></script>

<script src="{{asset('plugins/croppie/croppie.js')}}"></script>



<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.js"></script>

<script src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>

<!-- AdminLTE App -->
<script src="{{asset('AdminLTE/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('AdminLTE/dist/js/demo.js')}}"></script>
<!-- page script -->
</body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta name="description" content="{{!empty($description) ? $description : __('words.site_description')}}" />
  <meta name="author" content="Zagorcea Ion" />

  <title>{{!empty($title) ? $title : __('words.site_name')}}</title>

  @if(!empty($article_og))
    <meta property="og:url" content="{{ $article_og['url'] }}">
    <meta property="og:type" content="article">
    <meta property="og:title" content="{{ $article_og['title'] }}">
    <meta property="og:description" content="{{ $article_og['description'] }}">
    <meta property="og:image" content="{{ $article_og['image'] }}">
  @else
    <meta property="og:image" content="{{ asset('images/logo.png') }}">
  @endif

  @if (config('app.env') == 'production')
    <meta name="google-site-verification" content="0wPHbUzy4UXcm13PefIeX-lSrJGFpwN87JdEqVp2Ppg" />
  @endif

  <!-- Fav Icon -->
  <link rel="shortcut icon" href="{{asset('favicon.ico')}}">

  <!-- Bootstrap -->
  <link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('rs-plugin/css/settings.css')}}" rel="stylesheet">
  <link href="{{asset('css/font-awesome.css')}}" rel="stylesheet">

  <link href="{{asset('css/owl.carousel.css')}}" rel="stylesheet">
  <link href="{{asset('css/style.css')}}" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic' rel='stylesheet' type='text/css'>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">
  <link href="{{asset('plugins/Validation-Engine/css/validationEngine.jquery.css')}}" rel="stylesheet" type="text/css" />
  <link href="{{asset('plugins/noty/css/noty.css')}}" rel="stylesheet" type="text/css" />
  <link href="{{asset('plugins/noty/themes/mint.css')}}" rel="stylesheet" type="text/css" />
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="{{asset('plugins/Validation-Engine/js/jquery.validationEngine.js')}}"></script>
  <script src="{{asset('plugins/Validation-Engine/js/jquery.validationEngine-ro.js')}}"></script>

  @if (config('app.env') == 'production')
     <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-NSYLZ8X1TV"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-NSYLZ8X1TV');
    </script>
  @endif

</head>
<body>
<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v7.0&appId=1027156657756194&autoLogAppEvents=1"></script>

<!-- Topbar Start-->
<div id="topbar" class="site-topbar">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-8">
        <ul class="bar-info">
          <li><i class="fa fa-phone"></i><a href="tel:+37369363364" class="clear-style-link">069 363 364</a></li>
          <li><i class="fa fa-envelope-o" aria-hidden="true"></i><a href="mailto:info@lawoffice.md" class="clear-style-link">info@lawoffice.md</a></li>
        </ul>
      </div>
      <!-- <div class="col-md-6 col-sm-4">
        <ul class="topbar-links">
          <li>
            <a href="<?= route('setlocale', ['lang' => 'ro']) ?>">
              <img src="{{asset('images/ro.png')}}" style="width:20px; padding-right:5px; margin-top:-2px">RO
            </a>
          </li>
          <li>
            <a href="<?= route('setlocale', ['lang' => 'ru']) ?>">
                <img src="{{asset('images/ru.png')}}" style="width:20px; padding-right:5px; margin-top:-2px">RU
            </a>
        </ul>
      </div> -->
    </div>
  </div>
</div>
<!-- Topbar End --> 

<!-- Header Start-->
<div class="header">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-3">
        <div class="logo"> <a href="{{route('page.home')}}"><img src="{{asset('images/logo.png')}}" alt="" style="padding-top:10px"/> </a></div>
      </div>
      <div class="col-md-8 col-sm-9">
        <div class="navigationwrape">
          <div class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li> <a href="{{route('page.home')}}" class="{{!empty($active_page) &&  $active_page == 'homePage' ? 'active' : ''}}">{{__('words.nav_home')}}</a></li>
                <li> <a href="{{route('page.about')}}" class="{{!empty($active_page) &&  $active_page == 'aboutUs' ? 'active' : ''}}">{{__('words.nav_about')}}</a></li>
                <li> <a href="{{route('page.services')}}" class="{{!empty($active_page) &&  $active_page == 'services' ? 'active' : ''}}">{{__('words.nav_services')}}</a></li>
                <li> <a href="{{route('page.articles')}}" class="{{!empty($active_page) &&  $active_page == 'articles' ? 'active' : ''}}">{{__('words.nav_articles')}}</a></li>
                <li> <a href="{{route('page.consultation')}}" class="{{!empty($active_page) &&  $active_page == 'contact' ? 'active' : ''}}">{{__('words.nav_contact')}}</a></li>
              </ul>
            </div>
            <div class="clearfix"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Header End--> 

@yield('content')

<!-- ContactWrp start -->
<div class="contact-wrap">
  <div class="contact-left">
    <div class="container">
      <div class="row contact-info">
        <div class="col-md-6">
          <div class="headingTitle">
            <h1>{!! __('words.footer_contact_title') !!}</h1>
          </div>
          <p>{{__('words.footer_contact_description')}}</p>
          <h4>{{__('words.footer_contact_information')}}</h4>
          <div class="address">{!! __('words.footer_contact_address') !!}</div>
          <div class="phone">069 363 364</div>
          <div class="email">
            <a href="mailto:info@lawoffice.md" class="clear-style-link">info@lawoffice.md</a>
          </div>
          <div class="appointment"><a href="{{route('page.consultation')}}">{{__('words.consultation')}}</a></div>
        </div>
      </div>
    </div>
    <div class="right-map">
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2682.4050997262884!2d27.92484321589026!3d47.75419628576299!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40cb672f2bba7459%3A0x7727dbe60e49dddb!2zU3RyYWRhIFB1yJlraW4gNjIsIELEg2zIm2kgMzEwMCwg0JzQvtC70LTQsNCy0LjRjw!5e0!3m2!1sru!2s!4v1557131603722!5m2!1sru!2s" width="600" height="575" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>
</div>
<!-- ContactWrp end --> 

<!-- footer start -->

<div class="footer-wrap">
  <div class="container">
      <div class="row">
      <div class="col-md-{{!empty($footerServices) ? 4 : 6}}">
        <div class="left-col">
          <div class="footer-logo"><img src="{{asset('images/footer-logo.png')}}" alt=""></div>
          <p>{{__('words.site_description')}}</p>
          <ul class="footer-icons">
            <li><a href="https://www.facebook.com/Violina-Munteanu-108618654268408" target="_blank"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
            <li><a href="https://www.instagram.com/violinamunteanu/" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>

          </ul>
        </div>
      </div>
      <div class="col-md-{{!empty($footerServices) ? 4 : 6}} col-sm-6">
        <div class="footer-heading">{{__('words.navigation')}}</div>
        <ul class="footer-nav">
          <li> <a href="{{route('page.home')}}">{{__('words.nav_home')}}</a></li>
          <li> <a href="{{route('page.about')}}">{{__('words.nav_about')}}</a></li>
          <li> <a href="{{route('page.services')}}">{{__('words.nav_services')}}</a></li>
          <li> <a href="{{route('page.articles')}}">{{__('words.nav_articles')}}</a></li>
          <li> <a href="{{route('page.consultation')}}">{{__('words.nav_contact')}}</a></li>
        </ul>
      </div>
        @if(!empty($footerServices))
          <div class="col-md-4 col-sm-6">
            <div class="footer-heading">{{__('words.nav_services')}}</div>
            <ul class="footer-nav">
              @foreach($footerServices as $item)
                <li><a href="{{route('page.serviceDetails', ['service' => $item->alias])}}">{{$item->title}}</a></li>
              @endforeach
            </ul>
          </div>
        @endif
    </div>
    <div class="footer-service">
      <div class="copyright">Copyright © {{date('Y')}} Violina M.Munteanu, All Rights Reserved</div>
    </div>
  </div>
</div>

<!-- footer end --> 

<!--page scroll start-->
<div class="page-scroll scrollToTop"><a href="{{route('page.home')}}#"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></div>
<!--page scroll start-->

<!--page scroll start-->
<div class="page-scroll scrollToTop"><a href="{{route('page.home')}}#"><i class="fa fa-arrow-up" aria-hidden="true"></i></a></div>
<!--page scroll start-->


<!-- Include all compiled plugins (below), or include individual files as needed --> 
<script src="{{asset('plugins/noty/js/noty.js')}}"></script>
<script src="{{asset('js/jquery-2.1.4.min.js')}}"></script>
<script src="{{asset('js/bootstrap.min.js')}}"></script>
<!-- Load JS siles --> 
<script src="{{asset('js/owl.carousel.js')}}"></script>
<!-- SLIDER REVOLUTION SCRIPTS  --> 
<script src="{{asset('rs-plugin/js/jquery.themepunch.tools.min.js')}}"></script>
<script src="{{asset('rs-plugin/js/jquery.themepunch.revolution.min.js')}}"></script>
<!-- general script file --> 
<script src="{{asset('js/script.js')}}"></script>
 
</body>
</html>